// PDF generation for the v4.1.0 APST Evidence export — per-activity artefact and annual
// aggregate log. Both max 2 pages, both carry the required footer, neither stores server-side
// (generated on demand, streamed to the caller).

const PDFDocument = require('pdfkit');
const { VTLM_ALIGNMENT, AERO_CITATIONS, descriptorById } = require('./apstContent');

function footerText(date) {
  return `Generated by QuizPulse ${date.toISOString().slice(0, 10)}. For VIT professional learning evidence purposes only. Analytics are cohort-level; no individual student data is included.`;
}

// lineBreak: false is required — without it, footer text placed this close to the bottom
// margin can wrap and overflow past page.height, which makes pdfkit auto-paginate (grow the
// buffered page count) WHILE the caller is mid-loop over that same count, i.e. an infinite loop.
function renderFooter(doc) {
  const bottom = doc.page.height - doc.page.margins.bottom + 10;
  doc.fontSize(8).fillColor('#888').text(footerText(new Date()), doc.page.margins.left, bottom, {
    width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
    lineBreak: false,
  });
  doc.fillColor('black');
}

function collect(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}

// data: { teacherName, vitNumber, className, subject, activityName, pdType, date, descriptorIds,
//         durationHours, participation: {approved, responded}, correctness: {pctCorrect},
//         confidence: {confidentPct, unsurePct}, confidentButIncorrect, domainCoverage,
//         reflection1, reflection2 }
async function buildActivityPdf(data) {
  const doc = new PDFDocument({ margin: 50, bufferPages: true });
  const donePromise = collect(doc);

  doc.fontSize(16).text('VIT Evidence — Per-Activity Record', { align: 'left' });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#555');
  doc.text(`Activity: ${data.activityName}`);
  doc.text(`Date: ${data.date}`);
  doc.text(`Teacher: ${data.teacherName || '(not provided)'}${data.vitNumber ? '  |  VIT number: ' + data.vitNumber : ''}`);
  doc.text(`Class: ${data.className || '(unnamed class)'}   Subject: ${data.subject || '(no topic tag)'}`);
  doc.text(`PD type: ${data.pdType}   Duration: ${data.durationHours} hrs (${data.durationHours} = 0.6hrs × 1 quiz, editable)`);
  doc.fillColor('black');
  doc.moveDown(0.75);

  doc.fontSize(12).text('VTLM 2.0 alignment');
  doc.fontSize(10).fillColor('#333').text(VTLM_ALIGNMENT);
  doc.fillColor('black');
  doc.moveDown(0.5);

  doc.fontSize(12).text('APST descriptors addressed');
  doc.fontSize(9).fillColor('#333');
  for (const id of data.descriptorIds) {
    const d = descriptorById.get(id);
    if (!d) continue;
    doc.font('Helvetica-Bold').text(`${d.id} — ${d.focusArea} (${d.domain})`, { continued: false });
    doc.font('Helvetica').text(d.proficient);
    doc.moveDown(0.25);
  }
  doc.fillColor('black');

  const coverage = data.domainCoverage;
  const coverageStr = Object.keys(coverage).map(k => `${k} ${coverage[k] ? '✓' : '—'}`).join(' | ');
  doc.fontSize(9).fillColor('#555').text(`Domain coverage: ${coverageStr}`);
  doc.fillColor('black');
  doc.moveDown(0.5);

  doc.fontSize(9).fillColor('#555').text(`Citations: ${AERO_CITATIONS.join('; ')}`);
  doc.fillColor('black');
  doc.moveDown(0.5);

  doc.fontSize(12).text('Reflection — what did I learn?');
  doc.fontSize(10).fillColor('#333').text(data.reflection1);
  doc.fillColor('black');
  doc.moveDown(0.5);

  doc.fontSize(12).text('Reflection — how will I apply this?');
  doc.fontSize(10).fillColor('#333').text(data.reflection2);
  doc.fillColor('black');

  // Page 2 — analytics
  doc.addPage();
  doc.fontSize(14).text('Participation & assessment data');
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#333');
  doc.text(`Participation: ${data.participation.responded} of ${data.participation.approved} students responded.`);
  doc.text(`Cohort correctness: ${data.correctness.pctCorrect}%.`);
  doc.text(`Confidence: ${data.confidence.confidentPct}% confident, ${data.confidence.unsurePct}% unsure.`);
  doc.text(`Confident-but-incorrect responses (misconception signal): ${data.confidentButIncorrect}.`);
  doc.fillColor('black');

  const pageCount1 = doc.bufferedPageRange().count;
  for (let i = 0; i < pageCount1; i++) {
    doc.switchToPage(i);
    renderFooter(doc);
  }

  doc.end();
  return donePromise;
}

// data: { from, to, quizzes: [{name, sentAt, topicTag}], totalHours, classes: [names],
//         subjects: [topics], descriptorCounts: {id: count}, domainCoverage,
//         correctnessTrend: [{sentAt, pctCorrect}], confidentButIncorrectTotal }
async function buildAnnualLogPdf(data) {
  const doc = new PDFDocument({ margin: 50, bufferPages: true });
  const donePromise = collect(doc);

  doc.fontSize(16).text('VIT Evidence — Annual Aggregate PL Log');
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#555');
  doc.text(`Range: ${data.from} to ${data.to}`);
  doc.text(`${data.quizzes.length} QuizPulse sessions, ${data.totalHours} estimated hours of PL.`);
  doc.text(`Classes covered: ${data.classes.join(', ') || '(none)'}`);
  doc.text(`Subjects: ${data.subjects.join(', ') || '(none tagged)'}`);
  doc.fillColor('black');
  doc.moveDown(0.5);

  const coverage = data.domainCoverage;
  const coverageStr = Object.keys(coverage).map(k => `${k} ${coverage[k] ? '✓' : '—'}`).join(' | ');
  doc.fontSize(10).text(`Three-domain coverage: ${coverageStr}`);
  doc.moveDown(0.5);

  doc.fontSize(12).text('APST descriptors addressed (frequency)');
  doc.fontSize(9).fillColor('#333');
  const ids = Object.keys(data.descriptorCounts).sort();
  if (ids.length === 0) {
    doc.text('No topic-tagged quizzes in this range.');
  }
  for (const id of ids) {
    const d = descriptorById.get(id);
    doc.text(`${id}${d ? ' — ' + d.focusArea : ''}: ${data.descriptorCounts[id]}`);
  }
  doc.fillColor('black');
  doc.moveDown(0.5);

  doc.fontSize(12).text('Aggregate correctness trend');
  doc.fontSize(9).fillColor('#333');
  if (data.correctnessTrend.length === 0) {
    doc.text('No response data in this range.');
  } else {
    for (const point of data.correctnessTrend) {
      doc.text(`${point.sentAt.slice(0, 10)}: ${point.pctCorrect}% correct`);
    }
  }
  doc.fillColor('black');
  doc.moveDown(0.5);
  doc.fontSize(10).text(`Total confident-but-wrong instances across the period: ${data.confidentButIncorrectTotal}.`);

  doc.addPage();
  doc.fontSize(12).text('MyPD-ready summary block (copy/paste)');
  doc.moveDown(0.25);
  doc.fontSize(9).fillColor('#333').text(
    `Registration year PL summary: ${data.quizzes.length} QuizPulse retrieval-practice sessions between ${data.from} and ${data.to}, totalling approximately ${data.totalHours} hours. Aligned with VTLM 2.0 Supported Application — Revisit and review. Addresses APST across all three domains: ${coverageStr}. See attached per-activity artefacts for individual reflections and analytics.`
  );
  doc.fillColor('black');
  doc.moveDown(0.75);

  doc.fontSize(12).text('Reflection templates (per-activity level — not personalised at this aggregate level)');
  doc.fontSize(8).fillColor('#666');
  doc.text('See individual per-activity exports for personalised reflections. This aggregate log summarises activity only.');
  doc.fillColor('black');

  const pageCount2 = doc.bufferedPageRange().count;
  for (let i = 0; i < pageCount2; i++) {
    doc.switchToPage(i);
    renderFooter(doc);
  }

  doc.end();
  return donePromise;
}

module.exports = { buildActivityPdf, buildAnnualLogPdf, footerText };
